In [36]:
import numpy as np

In [38]:
mt = np.array([12,34,26,23,67])
print(mt)
type(mt)

[12 34 26 23 67]


numpy.ndarray

In [39]:
mtfloat = np.array([1,2,3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))

mtint = np.array([1,2,3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [40]:
mtnew = np.array([1.4,3.6,-5.1,9.42,4.99999])
print(mtnew)
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4      3.6     -5.1      9.42     4.99999]
[ 1  3 -5  9  4]


In [41]:
mt5 = np.array([1,2,3,4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [42]:
mt7 = np.array([[7,58,4], [25,55,5], [85,65,66]])
print(mt7)

[[ 7 58  4]
 [25 55  5]
 [85 65 66]]


In [43]:
vazio = np.empty([3,2], dtype = int)
print(vazio)
print('/~/~/~/~/~/~/~/~/~/~/~/~')
zeros = np.zeros([4,3])
print(zeros)
print('/~/~/~/~/~/~/~/~/~/~/~/~')
um = np.ones([5,7])
print(um)
print('/~/~/~/~/~/~/~/~/~/~/~/~')
diagonal = np.eye(5)
print(diagonal)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]
/~/~/~/~/~/~/~/~/~/~/~/~
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
/~/~/~/~/~/~/~/~/~/~/~/~
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
/~/~/~/~/~/~/~/~/~/~/~/~
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [44]:
ale = np.random.random((5))
print(ale)
print('/~/~/~/~/~/~/~/~/~/~/~/~')
ale2 = np.random.randn((5))
print(ale2)
print('/~/~/~/~/~/~/~/~/~/~/~/~')
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.84104922 0.3286051  0.72284744 0.08951859 0.75687807]
/~/~/~/~/~/~/~/~/~/~/~/~
[-0.27967756 -0.38426688  0.02697463 -0.24316745 -0.18518634]
/~/~/~/~/~/~/~/~/~/~/~/~
[[3.33307371 6.82861629 8.74261457 0.47371583]
 [2.76708301 6.02842937 0.78114211 8.0424534 ]
 [2.5658833  9.36146447 9.159791   1.56540874]]


In [45]:
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)
print('/~/~/~/~/~/~/~/~/~/~/~/~')
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
/~/~/~/~/~/~/~/~/~/~/~/~
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [46]:
j = np.array([11,21,34,56,99,99,11,21,46,12,78,34])
j = np.unique(j)
print(j)

[11 12 21 34 46 56 78 99]


In [47]:
k = np.array([[35,65,13], [29, 97,23], [43,78,31]])
print(k)
print(k[0][1])
print(k.shape)

[[35 65 13]
 [29 97 23]
 [43 78 31]]
65
(3, 3)


In [48]:
print(k.max())
print(k.min())
print(k.sum())
print(k.mean())
print(k.std())

97
13
414
46.0
26.34809712715934


In [49]:
k1 = np.array([1,4,9,16,25,36])
print(np.sqrt(k1))
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [50]:
m = np.array([1,2,3,4,5,6])
print(m[1])
print('------')
print(m[0:2])
print('------')
print(m[1:])
print('------')
print(m[-3:])

2
------
[1 2]
------
[2 3 4 5 6]
------
[4 5 6]


In [53]:
l = np.array([[4,5], [6,1], [7,4]])
print(l)
print('------')
l_linha_1 = l[0, :]
print(l_linha_1)
print('------')
l_linha_2 = l[1, :]
print(l_linha_2)
print('------')
l_linha_3 = l[2, :]
print(l_linha_3)
print('------')
l_coluna_1 = l[:, 0]
print(l_coluna_1)
print('------')
l_coluna_2 = l[:, 1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
------
[4 5]
------
[6 1]
------
[7 4]
------
[4 6 7]
------
[5 1 4]


In [54]:
n = np.array([[1,2], [3,4]])
o = np.array([[5,6], [7,8]])
res1 = n+o
print(res1)
print('----------')
res2 = n*o
print(res2)
print('----------')
p = np.array([[1,2], [3,4], [5,6]])
q = np.array([[2,1]])
print(p+q)

[[ 6  8]
 [10 12]]
----------
[[ 5 12]
 [21 32]]
----------
[[3 3]
 [5 5]
 [7 7]]


In [58]:
f = np.arange(15).reshape((3,5))
print(f)
s = f.T
print(s)
t = f.transpose(1,0)
print(t)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
